// -----------------------------------------------------------------------------
// cordic_rom.v
// The CORDIC micro-rotation schedule ROM. One 64-bit word per step:
//   [63:32] = shift amount i, [31:0] = fixed rotation angle in Q4.28
//     - atan(2^-i)  for the circular steps (indices 0 .. NC-1)
//     - atanh(2^-i) for the hyperbolic steps (indices NC .. NROM-1)
// The contents are generated by sw/sfu_host (sfu_emit_rom) from the very same
// libm-derived, Q4.28-rounded integers the software golden iterates on, so the
// hardware is bit-exact against the model. Loaded via $readmemh at elaboration -
// a synthesizable ROM initialisation.
// -----------------------------------------------------------------------------
`default_nettype none

module cordic_rom #(
    parameter        ROMFILE = "tb/vectors/cordic_rom.hex"
) (
    input  wire [7:0]         idx,
    output wire [5:0]         shf,
    output wire signed [31:0] ang
);
`include "sfu_const.vh"

    reg [63:0] mem [0:NROM-1];
    initial $readmemh(ROMFILE, mem);

    assign shf = mem[idx][37:32];    // shift amount (0..27 fits 6 bits)
    assign ang = mem[idx][31:0];     // rotation angle, Q4.28 (always positive)
endmodule

`default_nettype wire
