#!/usr/bin/env python3
"""Turn a simulation log + software-baseline file into results/metrics.md.

Only measured quantities are emitted. Derived numbers (MAC/cycle, speedup) are
computed from those measurements; nothing is hard-coded.

usage: extract_metrics.py <sim.log> <sw_metrics.txt>
"""
import sys


def parse_results(path):
    d = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("RESULT "):
                _, key, val = line.split(None, 2)
                d[key] = int(val)
    return d


def parse_kv(path):
    d = {}
    try:
        with open(path) as f:
            for line in f:
                parts = line.split()
                if len(parts) == 2:
                    k, v = parts
                    try:
                        d[k] = float(v) if "." in v else int(v)
                    except ValueError:
                        pass
    except FileNotFoundError:
        pass
    return d


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: extract_metrics.py <sim.log> <sw_metrics.txt>")
    hw = parse_results(sys.argv[1])
    sw = parse_kv(sys.argv[2])

    n = hw.get("n_dim", 0)
    peak_cap = n * n                                   # MAC/cycle at 100% array use

    def mpc(m, c):
        return (m / c) if c else 0.0

    rep_mpc = mpc(hw.get("rep_macs", 0), hw.get("rep_cycles", 0))
    big_mpc = mpc(hw.get("big_macs", 0), hw.get("big_cycles", 0))
    all_mpc = mpc(hw.get("all_macs", 0), hw.get("all_cycles", 0))

    total_mism = hw.get("total_mismatches", -1)
    proto = hw.get("proto_errors", -1)

    out = []
    out.append("# Measured results - Day 2 systolic GEMM accelerator\n")
    out.append("Generated by `scripts/extract_metrics.py` from `results/sim.log` "
               "and `tb/vectors/sw_metrics.txt`. All hardware numbers are cycle "
               "counts read from the accelerator's `CYCLES` register in the "
               "Icarus simulation.\n")

    out.append("## Configuration\n")
    out.append("| Parameter | Value |")
    out.append("|---|---|")
    out.append(f"| Array dimension N | {n} x {n} ({peak_cap} MACs) |")
    out.append(f"| Operand width | {hw.get('data_width','?')} bits, signed |")
    out.append(f"| Accumulator/result width | {hw.get('acc_width','?')} bits, signed |")
    out.append(f"| Max K per run (KMAX) | {hw.get('kmax','?')} |")
    out.append("| Control interface | Wishbone B4 classic |")
    out.append("")

    out.append("## Verification\n")
    out.append("| Check | Value |")
    out.append("|---|---|")
    out.append(f"| Jobs run | {hw.get('total_jobs','?')} |")
    out.append(f"| Output elements checked vs golden | {hw.get('total_output_checks','?')} |")
    out.append(f"| Mismatches | {total_mism} |")
    out.append(f"| Wishbone / protocol violations | {proto} |")
    out.append("")

    out.append("## Throughput\n")
    out.append("The array performs up to N*N = "
               f"{peak_cap} multiply-accumulates every cycle at steady state; the "
               "fixed fill/drain of `2N` cycles and the one-cycle setup per run "
               "are the only overhead, so utilization rises with K.\n")
    out.append("| Workload | MACs | Cycles | MAC/cycle | Array utilization |")
    out.append("|---|---|---|---|---|")
    out.append(f"| Peak single tile (K=KMAX) | {hw.get('rep_macs',0)} | {hw.get('rep_cycles',0)} | "
               f"{rep_mpc:.2f} | {100.0*rep_mpc/peak_cap if peak_cap else 0:.1f}% |")
    out.append(f"| Large tiles (K >= KMAX/2) | {hw.get('big_macs',0)} | {hw.get('big_cycles',0)} | "
               f"{big_mpc:.2f} | {100.0*big_mpc/peak_cap if peak_cap else 0:.1f}% |")
    out.append(f"| All jobs (K from 1..KMAX) | {hw.get('all_macs',0)} | {hw.get('all_cycles',0)} | "
               f"{all_mpc:.2f} | {100.0*all_mpc/peak_cap if peak_cap else 0:.1f}% |")
    out.append("")

    out.append("## Hardware vs software baseline\n")
    out.append("Software baseline: a scalar CPU computing the same products does "
               "one multiply-accumulate per cycle at best, so its cycle count "
               "equals the MAC count. The speedup is therefore the measured "
               "hardware MAC/cycle.\n")
    out.append("| Metric | Value |")
    out.append("|---|---|")
    out.append(f"| Scalar model | 1.00 MAC/cycle |")
    out.append(f"| Hardware, peak tile | {rep_mpc:.2f} MAC/cycle -> {rep_mpc:.2f}x |")
    out.append(f"| Hardware, large tiles | {big_mpc:.2f} MAC/cycle -> {big_mpc:.2f}x |")
    if "total_tile_macs" in sw:
        out.append(f"| Total MACs exercised | {sw['total_tile_macs']} |")
    if "sw_host_ns_per_mac" in sw:
        out.append(f"| Host reference (informational) | "
                   f"{sw['sw_host_ns_per_mac']:.5f} ns/MAC (compiled C on the build host) |")
    out.append("")

    verdict = "PASS" if (total_mism == 0 and proto == 0) else "FAIL"
    out.append(f"**Overall: {verdict}**")
    print("\n".join(out))


if __name__ == "__main__":
    main()
