#!/usr/bin/env python3
"""Turn a simulation log + software-baseline file into results/metrics.md.

Only measured quantities are emitted. Derived numbers (throughput, speedup) are
computed from those measurements; nothing is hard-coded.

usage: extract_metrics.py <sim.log> <sw_metrics.txt>
"""
import sys


def parse_results(path):
    d = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("RESULT "):
                _, key, val = line.split(None, 2)
                d[key] = int(val)
    return d


def parse_kv(path):
    d = {}
    try:
        with open(path) as f:
            for line in f:
                parts = line.split()
                if len(parts) == 2:
                    k, v = parts
                    try:
                        d[k] = float(v) if "." in v else int(v)
                    except ValueError:
                        pass
    except FileNotFoundError:
        pass
    return d


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: extract_metrics.py <sim.log> <sw_metrics.txt>")
    hw = parse_results(sys.argv[1])
    sw = parse_kv(sys.argv[2])

    taps = hw.get("taps", 0)
    bb_s = hw.get("bb_samples", 0)
    bb_c = hw.get("bb_cycles", 0)
    rep_len = hw.get("rep_len", 0)
    rep_cyc = hw.get("rep_cycles", 0)
    rep_lat = hw.get("rep_latency", 0)

    # Headline throughput/speedup come from the largest back-to-back job, whose
    # length amortizes fixed per-job setup so the figure reflects steady state.
    rep_cps = (rep_cyc / rep_len) if rep_len else 0.0     # HW cycles / sample
    thr = (rep_len / rep_cyc) if rep_cyc else 0.0         # samples / cycle
    macs_cyc = thr * taps                                  # MACs / cycle
    hw_cps = rep_cps
    sw_cps = float(taps)                                   # scalar model: taps MACs/sample
    speedup = (sw_cps / hw_cps) if hw_cps else 0.0
    agg_thr = (bb_s / bb_c) if bb_c else 0.0               # across all bb jobs (incl. setup)

    total_mism = hw.get("total_mismatches", -1)
    proto = hw.get("proto_errors", -1)
    tlast = hw.get("tlast_errors", -1)

    out = []
    out.append("# Measured results - Day 1 FIR accelerator\n")
    out.append("Generated by `scripts/extract_metrics.py` from `results/sim.log` "
               "and `tb/vectors/sw_metrics.txt`. All hardware numbers are cycle "
               "counts taken directly from the Icarus simulation.\n")

    out.append("## Configuration\n")
    out.append("| Parameter | Value |")
    out.append("|---|---|")
    out.append(f"| Taps | {taps} |")
    out.append(f"| Data width | {hw.get('data_width','?')} bits |")
    out.append(f"| Coefficient width | {hw.get('coef_width','?')} bits |")
    out.append(f"| Accumulator/result width | {hw.get('acc_width','?')} bits |")
    out.append(f"| FIFO depth | {hw.get('fifo_depth','?')} |")
    out.append("")

    out.append("## Verification\n")
    out.append("| Check | Value |")
    out.append("|---|---|")
    out.append(f"| Jobs run | {hw.get('total_jobs','?')} |")
    out.append(f"| Samples checked | {hw.get('total_samples','?')} |")
    out.append(f"| Output mismatches vs golden | {total_mism} |")
    out.append(f"| AXI protocol violations | {proto} |")
    out.append(f"| TLAST framing errors | {tlast} |")
    if "input_backpressure_cycles" in hw:
        out.append(f"| Input backpressure exercised | {hw['input_backpressure_cycles']} cycles |")
    out.append("")

    out.append("## Throughput and latency\n")
    out.append("| Metric | Value | How measured |")
    out.append("|---|---|---|")
    out.append(f"| Steady-state throughput | {thr:.4f} samples/cycle | "
               f"largest back-to-back job: {rep_len} samples in {rep_cyc} cycles (START->DONE) |")
    out.append(f"| Compute density | {macs_cyc:.2f} MAC/cycle | throughput x taps |")
    out.append(f"| Per-sample cost | {rep_cps:.3f} cycles/sample | same job |")
    out.append(f"| Fill latency | {rep_lat} cycles | first input accepted -> first output valid |")
    out.append(f"| Sustained (all bb jobs) | {agg_thr:.4f} samples/cycle | "
               f"{bb_s} samples over {bb_c} cycles, includes per-job CSR setup |")
    out.append("")

    out.append("## Hardware vs software baseline\n")
    out.append("Software baseline: a scalar CPU computing the same streaming FIR "
               "performs `taps` multiply-accumulates per output sample "
               f"(= {taps} cycles/sample on an ideal 1-MAC/cycle core). The "
               "accelerator issues all taps in parallel every cycle.\n")
    out.append("| Metric | Value |")
    out.append("|---|---|")
    out.append(f"| Software model | {sw_cps:.1f} cycles/sample ({taps} MACs) |")
    out.append(f"| Hardware measured | {hw_cps:.3f} cycles/sample |")
    out.append(f"| Speedup | {speedup:.2f}x |")
    if "total_macs" in sw:
        out.append(f"| Total MACs in batch | {sw['total_macs']} |")
    if "sw_host_ns_per_sample" in sw:
        out.append(f"| Host reference (informational) | "
                   f"{sw['sw_host_ns_per_sample']:.3f} ns/sample (compiled C on the build host) |")
    out.append("")

    verdict = "PASS" if (total_mism == 0 and proto == 0 and tlast == 0) else "FAIL"
    out.append(f"**Overall: {verdict}**")
    print("\n".join(out))


if __name__ == "__main__":
    main()
